### list all filenames of the directory here ###
SET(GROUP PERSISTENCE)

SET(DIRECTORY "${CMAKE_SOURCE_DIR}/include/UNIPAX/${GROUP}")

FILE(GLOB HEADERS_LIST "${DIRECTORY}/*.h")	

FILE(GLOB MOCS "${DIRECTORY}/*.h")

LIST(APPEND MOC_HEADERS_LIST ${MOCS})

ADD_UNIPAX_HEADERS("${GROUP}" "${HEADERS_LIST}")

IF (database STREQUAL "oracle")
	INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/PERSISTENCE/ORACLE/sources.cmake)
ENDIF (database STREQUAL "oracle")

IF (NOT (database STREQUAL "oracle"))
	INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/PERSISTENCE/MYSQL/sources.cmake)
ENDIF (NOT (database STREQUAL "oracle"))
