/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `BindingFeature_bindsTo`;

DROP TABLE IF EXISTS `BindingFeature`;

CREATE TABLE `BindingFeature` (
  `unipaxId` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `intraMolecular` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `BindingFeature_bindsTo` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NULL,
  CONSTRAINT `BindingFeature_bindsTo_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `BindingFeature` (`unipaxId`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `BindingFeature_bindsTo_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `BindingFeature` (`unipaxId`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `BindingFeature_bindsTo` (`object_id`);

CREATE INDEX `index_i`
  ON `BindingFeature_bindsTo` (`index`);

ALTER TABLE `BindingFeature`
  ADD CONSTRAINT `BindingFeature_unipaxId_fk`
    FOREIGN KEY (`unipaxId`)
    REFERENCES `EntityFeature` (`unipaxId`)
    ON DELETE CASCADE;

