/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `PathwayStep_nextStep`;

DROP TABLE IF EXISTS `PathwayStep_evidence`;

DROP TABLE IF EXISTS `PathwayStep_stepProcess`;

DROP TABLE IF EXISTS `PathwayStep_comment`;

DROP TABLE IF EXISTS `PathwayStep`;

CREATE TABLE `PathwayStep` (
  `unipaxId` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `unipaxSource` BIGINT UNSIGNED NULL,
  `typeid` VARCHAR(255) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `PathwayStep_comment` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PathwayStep_comment_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PathwayStep` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PathwayStep_comment` (`object_id`);

CREATE INDEX `index_i`
  ON `PathwayStep_comment` (`index`);

CREATE TABLE `PathwayStep_stepProcess` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NULL,
  CONSTRAINT `PathwayStep_stepProcess_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PathwayStep` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PathwayStep_stepProcess` (`object_id`);

CREATE INDEX `index_i`
  ON `PathwayStep_stepProcess` (`index`);

CREATE TABLE `PathwayStep_evidence` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NULL,
  CONSTRAINT `PathwayStep_evidence_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PathwayStep` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PathwayStep_evidence` (`object_id`);

CREATE INDEX `index_i`
  ON `PathwayStep_evidence` (`index`);

CREATE TABLE `PathwayStep_nextStep` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NULL,
  CONSTRAINT `PathwayStep_nextStep_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PathwayStep` (`unipaxId`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `PathwayStep_nextStep_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `PathwayStep` (`unipaxId`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PathwayStep_nextStep` (`object_id`);

CREATE INDEX `index_i`
  ON `PathwayStep_nextStep` (`index`);

/*
ALTER TABLE `PathwayStep`
  ADD CONSTRAINT `PathwayStep_unipaxSource_fk`
    FOREIGN KEY (`unipaxSource`)
    REFERENCES `ImportSource` (`unipaxId`)
*/

/*
ALTER TABLE `PathwayStep_stepProcess`
  ADD CONSTRAINT `PathwayStep_stepProcess_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Entity` (`unipaxId`)
*/

/*
ALTER TABLE `PathwayStep_evidence`
  ADD CONSTRAINT `PathwayStep_evidence_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Evidence` (`unipaxId`)
*/

