/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `PublicationXref_url`;

DROP TABLE IF EXISTS `PublicationXref_source`;

DROP TABLE IF EXISTS `PublicationXref_author`;

DROP TABLE IF EXISTS `PublicationXref`;

CREATE TABLE `PublicationXref` (
  `unipaxId` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `title` TEXT NOT NULL,
  `year` INT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `PublicationXref_author` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PublicationXref_author_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PublicationXref` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PublicationXref_author` (`object_id`);

CREATE INDEX `index_i`
  ON `PublicationXref_author` (`index`);

CREATE TABLE `PublicationXref_source` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PublicationXref_source_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PublicationXref` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PublicationXref_source` (`object_id`);

CREATE INDEX `index_i`
  ON `PublicationXref_source` (`index`);

CREATE TABLE `PublicationXref_url` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `PublicationXref_url_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `PublicationXref` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `PublicationXref_url` (`object_id`);

CREATE INDEX `index_i`
  ON `PublicationXref_url` (`index`);

ALTER TABLE `PublicationXref`
  ADD CONSTRAINT `PublicationXref_unipaxId_fk`
    FOREIGN KEY (`unipaxId`)
    REFERENCES `Xref` (`unipaxId`)
    ON DELETE CASCADE;

