// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/DnaRegionReference-odb.hxx>

#include <cassert>
#include <cstring> // std::memcpy

#include <odb/cache-traits.hxx>
#include <odb/details/shared-ptr.hxx>

#include <odb/oracle/binding.hxx>
#include <odb/oracle/traits.hxx>
#include <odb/oracle/database.hxx>
#include <odb/oracle/transaction.hxx>
#include <odb/oracle/connection.hxx>
#include <odb/oracle/statement.hxx>
#include <odb/oracle/statement-cache.hxx>
#include <odb/oracle/object-statements.hxx>
#include <odb/oracle/container-statements.hxx>
#include <odb/oracle/exceptions.hxx>
#include <odb/oracle/result.hxx>

namespace odb
{
  // DnaRegionReference
  //

  const char query_columns_base< ::UniPAX::DnaRegionReference >::regionType_alias_[] = "\"regionType\"";

  const char query_columns_base< ::UniPAX::DnaRegionReference >::organism_alias_[] = "\"organism\"";

  // comment
  //

  const char access::object_traits< ::UniPAX::DnaRegionReference >::comment_traits::select_all_statement[] =
  "SELECT "
  "\"DnaRegionReference_comment\".\"index\","
  "\"DnaRegionReference_comment\".\"value\""
  " FROM \"DnaRegionReference_comment\" WHERE \"DnaRegionReference_comment\".\"object_id\"=:1"
  " ORDER BY \"DnaRegionReference_comment\".\"index\""
  ;

  const char access::object_traits< ::UniPAX::DnaRegionReference >::comment_traits::insert_one_statement[] =
  "INSERT INTO \"DnaRegionReference_comment\" ("
  "\"object_id\","
  "\"index\","
  "\"value\")"
  " VALUES (:1,:2,:3)";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::comment_traits::delete_all_statement[] =
  "DELETE FROM \"DnaRegionReference_comment\""
  " WHERE \"object_id\"=:1";

  // id_memberEntityReferences
  //

  const char access::object_traits< ::UniPAX::DnaRegionReference >::id_memberEntityReferences_traits::select_all_statement[] =
  "SELECT "
  "\"DnaRegionReference_id_memberEn\".\"index\","
  "\"DnaRegionReference_id_memberEn\".\"value\""
  " FROM \"DnaRegionReference_id_memberEn\" WHERE \"DnaRegionReference_id_memberEn\".\"object_id\"=:1"
  " ORDER BY \"DnaRegionReference_id_memberEn\".\"index\""
  ;

  const char access::object_traits< ::UniPAX::DnaRegionReference >::id_memberEntityReferences_traits::insert_one_statement[] =
  "INSERT INTO \"DnaRegionReference_id_memberEn\" ("
  "\"object_id\","
  "\"index\","
  "\"value\")"
  " VALUES (:1,:2,:3)";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::id_memberEntityReferences_traits::delete_all_statement[] =
  "DELETE FROM \"DnaRegionReference_id_memberEn\""
  " WHERE \"object_id\"=:1";

  // evidence
  //

  const char access::object_traits< ::UniPAX::DnaRegionReference >::evidence_traits::select_all_statement[] =
  "SELECT "
  "\"DnaRegionReference_evidence\".\"index\","
  "\"DnaRegionReference_evidence\".\"value\""
  " FROM \"DnaRegionReference_evidence\" WHERE \"DnaRegionReference_evidence\".\"object_id\"=:1"
  " ORDER BY \"DnaRegionReference_evidence\".\"index\""
  ;

  const char access::object_traits< ::UniPAX::DnaRegionReference >::evidence_traits::insert_one_statement[] =
  "INSERT INTO \"DnaRegionReference_evidence\" ("
  "\"object_id\","
  "\"index\","
  "\"value\")"
  " VALUES (:1,:2,:3)";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::evidence_traits::delete_all_statement[] =
  "DELETE FROM \"DnaRegionReference_evidence\""
  " WHERE \"object_id\"=:1";

  // id_xref
  //

  const char access::object_traits< ::UniPAX::DnaRegionReference >::id_xref_traits::select_all_statement[] =
  "SELECT "
  "\"DnaRegionReference_id_xref\".\"index\","
  "\"DnaRegionReference_id_xref\".\"value\""
  " FROM \"DnaRegionReference_id_xref\" WHERE \"DnaRegionReference_id_xref\".\"object_id\"=:1"
  " ORDER BY \"DnaRegionReference_id_xref\".\"index\""
  ;

  const char access::object_traits< ::UniPAX::DnaRegionReference >::id_xref_traits::insert_one_statement[] =
  "INSERT INTO \"DnaRegionReference_id_xref\" ("
  "\"object_id\","
  "\"index\","
  "\"value\")"
  " VALUES (:1,:2,:3)";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::id_xref_traits::delete_all_statement[] =
  "DELETE FROM \"DnaRegionReference_id_xref\""
  " WHERE \"object_id\"=:1";

  // name
  //

  const char access::object_traits< ::UniPAX::DnaRegionReference >::name_traits::select_all_statement[] =
  "SELECT "
  "\"DnaRegionReference_name\".\"index\","
  "\"DnaRegionReference_name\".\"value\""
  " FROM \"DnaRegionReference_name\" WHERE \"DnaRegionReference_name\".\"object_id\"=:1"
  " ORDER BY \"DnaRegionReference_name\".\"index\""
  ;

  const char access::object_traits< ::UniPAX::DnaRegionReference >::name_traits::insert_one_statement[] =
  "INSERT INTO \"DnaRegionReference_name\" ("
  "\"object_id\","
  "\"index\","
  "\"value\")"
  " VALUES (:1,:2,:3)";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::name_traits::delete_all_statement[] =
  "DELETE FROM \"DnaRegionReference_name\""
  " WHERE \"object_id\"=:1";

  void access::object_traits< ::UniPAX::DnaRegionReference >::
  bind (oracle::bind* b, image_type& i, oracle::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace oracle;

    std::size_t n (0);

    // EntityReference base
    //
    object_traits< ::UniPAX::EntityReference >::bind (b + n, i, sk);
    n += 6UL - (
      sk == statement_select ? 0 : (
        sk == statement_insert ? 0 : 1UL));

    // sequence
    //
    b[n].type = oracle::bind::string;
    b[n].buffer = i.sequence_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.sequence_value));
    b[n].size = &i.sequence_size;
    b[n].indicator = &i.sequence_indicator;
    n++;

    // id_subRegion
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.id_subRegion_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.id_subRegion_value));
    b[n].size = &i.id_subRegion_size;
    b[n].indicator = &i.id_subRegion_indicator;
    n++;

    // regionType
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.regionType_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.regionType_value));
    b[n].size = &i.regionType_size;
    b[n].indicator = &i.regionType_indicator;
    n++;

    // organism
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.organism_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.organism_value));
    b[n].size = &i.organism_size;
    b[n].indicator = &i.organism_indicator;
    n++;

    // id_absoluteRegion
    //
    b[n].type = oracle::bind::number;
    b[n].buffer = i.id_absoluteRegion_value;
    b[n].capacity = static_cast<ub4> (sizeof (i.id_absoluteRegion_value));
    b[n].size = &i.id_absoluteRegion_size;
    b[n].indicator = &i.id_absoluteRegion_indicator;
    n++;
  }

  bool access::object_traits< ::UniPAX::DnaRegionReference >::
  init (image_type& i, const object_type& o, oracle::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace oracle;

    if (i.change_callback_.callback != 0)
      (i.change_callback_.callback) (i.change_callback_.context);

    bool grew (false);

    // EntityReference base
    //
    if (object_traits< ::UniPAX::EntityReference >::init (i, o, sk))
      grew = true;

    // sequence
    //
    {
      bool is_null;
      std::size_t size (0);
      oracle::value_traits<
          ::std::string,
          oracle::id_string >::set_image (
        i.sequence_value,
        sizeof (i.sequence_value),
        size,
        is_null,
        o.sequence);
      i.sequence_size = static_cast<ub2> (size);
      i.sequence_indicator = is_null ? -1 : 0;
    }

    // id_subRegion
    //
    {
      bool is_null;
      std::size_t size (0);
      oracle::value_traits<
          long long unsigned int,
          oracle::id_big_int >::set_image (
        i.id_subRegion_value,
        size,
        is_null,
        o.id_subRegion);
      i.id_subRegion_size = static_cast<ub2> (size);
      i.id_subRegion_indicator = is_null ? -1 : 0;
    }

    // regionType
    //
    {
      typedef object_traits< ::UniPAX::SequenceRegionVocabulary > obj_traits;
      typedef pointer_traits< ::boost::shared_ptr< ::UniPAX::SequenceRegionVocabulary > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (o.regionType));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (o.regionType)));

        std::size_t size (0);
        oracle::value_traits<
            obj_traits::id_type,
            oracle::id_big_int >::set_image (
          i.regionType_value,
          size,
          is_null,
          id);
        i.regionType_size = static_cast<ub2> (size);
      }

      i.regionType_indicator = is_null ? -1 : 0;
    }

    // organism
    //
    {
      typedef object_traits< ::UniPAX::BioSource > obj_traits;
      typedef pointer_traits< ::boost::shared_ptr< ::UniPAX::BioSource > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (o.organism));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (o.organism)));

        std::size_t size (0);
        oracle::value_traits<
            obj_traits::id_type,
            oracle::id_big_int >::set_image (
          i.organism_value,
          size,
          is_null,
          id);
        i.organism_size = static_cast<ub2> (size);
      }

      i.organism_indicator = is_null ? -1 : 0;
    }

    // id_absoluteRegion
    //
    {
      bool is_null;
      std::size_t size (0);
      oracle::value_traits<
          long long unsigned int,
          oracle::id_big_int >::set_image (
        i.id_absoluteRegion_value,
        size,
        is_null,
        o.id_absoluteRegion);
      i.id_absoluteRegion_size = static_cast<ub2> (size);
      i.id_absoluteRegion_indicator = is_null ? -1 : 0;
    }

    return grew;
  }

  void access::object_traits< ::UniPAX::DnaRegionReference >::
  init (object_type& o, const image_type& i, database& db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // EntityReference base
    //
    object_traits< ::UniPAX::EntityReference >::init (o, i, db);

    // sequence
    //
    oracle::value_traits<
        ::std::string,
        oracle::id_string >::set_value (
      o.sequence,
      i.sequence_value,
      i.sequence_size,
      i.sequence_indicator == -1);

    // id_subRegion
    //
    oracle::value_traits<
        long long unsigned int,
        oracle::id_big_int >::set_value (
      o.id_subRegion,
      i.id_subRegion_value,
      i.id_subRegion_size,
      i.id_subRegion_indicator == -1);

    // regionType
    //
    {
      typedef object_traits< ::UniPAX::SequenceRegionVocabulary > obj_traits;
      typedef pointer_traits< ::boost::shared_ptr< ::UniPAX::SequenceRegionVocabulary > > ptr_traits;

      if (i.regionType_indicator == -1)
        o.regionType = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        oracle::value_traits<
            obj_traits::id_type,
            oracle::id_big_int >::set_value (
          id,
          i.regionType_value,
          i.regionType_size,
          i.regionType_indicator == -1);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        o.regionType = ptr_traits::pointer_type (
          db.load< obj_traits::object_type > (id));
      }
    }

    // organism
    //
    {
      typedef object_traits< ::UniPAX::BioSource > obj_traits;
      typedef pointer_traits< ::boost::shared_ptr< ::UniPAX::BioSource > > ptr_traits;

      if (i.organism_indicator == -1)
        o.organism = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        oracle::value_traits<
            obj_traits::id_type,
            oracle::id_big_int >::set_value (
          id,
          i.organism_value,
          i.organism_size,
          i.organism_indicator == -1);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        o.organism = ptr_traits::pointer_type (
          db.load< obj_traits::object_type > (id));
      }
    }

    // id_absoluteRegion
    //
    oracle::value_traits<
        long long unsigned int,
        oracle::id_big_int >::set_value (
      o.id_absoluteRegion,
      i.id_absoluteRegion_value,
      i.id_absoluteRegion_size,
      i.id_absoluteRegion_indicator == -1);
  }

  struct access::object_traits< ::UniPAX::DnaRegionReference >::container_statement_cache_type
  {
    oracle::container_statements_impl< comment_traits > comment;
    oracle::container_statements_impl< id_memberEntityReferences_traits > id_memberEntityReferences;
    oracle::container_statements_impl< evidence_traits > evidence;
    oracle::container_statements_impl< id_xref_traits > id_xref;
    oracle::container_statements_impl< name_traits > name;

    container_statement_cache_type (oracle::connection& c)
    : comment (c),
      id_memberEntityReferences (c),
      evidence (c),
      id_xref (c),
      name (c)
    {
    }
  };

  const char access::object_traits< ::UniPAX::DnaRegionReference >::persist_statement[] =
  "INSERT INTO \"DnaRegionReference\" ("
  "\"unipaxId\","
  "\"unipaxSource\","
  "\"entityReferenceType\","
  "\"id_entityFeature\","
  "\"standardName\","
  "\"displayName\","
  "\"sequence\","
  "\"id_subRegion\","
  "\"regionType\","
  "\"organism\","
  "\"id_absoluteRegion\")"
  " VALUES (:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11)";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::find_statement[] =
  "SELECT "
  "\"DnaRegionReference\".\"unipaxId\","
  "\"DnaRegionReference\".\"unipaxSource\","
  "\"DnaRegionReference\".\"entityReferenceType\","
  "\"DnaRegionReference\".\"id_entityFeature\","
  "\"DnaRegionReference\".\"standardName\","
  "\"DnaRegionReference\".\"displayName\","
  "\"DnaRegionReference\".\"sequence\","
  "\"DnaRegionReference\".\"id_subRegion\","
  "\"DnaRegionReference\".\"regionType\","
  "\"DnaRegionReference\".\"organism\","
  "\"DnaRegionReference\".\"id_absoluteRegion\""
  " FROM \"DnaRegionReference\""
  " WHERE \"DnaRegionReference\".\"unipaxId\"=:1";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::update_statement[] =
  "UPDATE \"DnaRegionReference\" SET "
  "\"unipaxSource\"=:1,"
  "\"entityReferenceType\"=:2,"
  "\"id_entityFeature\"=:3,"
  "\"standardName\"=:4,"
  "\"displayName\"=:5,"
  "\"sequence\"=:6,"
  "\"id_subRegion\"=:7,"
  "\"regionType\"=:8,"
  "\"organism\"=:9,"
  "\"id_absoluteRegion\"=:10"
  " WHERE \"unipaxId\"=:11";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::erase_statement[] =
  "DELETE FROM \"DnaRegionReference\""
  " WHERE \"unipaxId\"=:1";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::query_statement[] =
  "SELECT "
  "\"DnaRegionReference\".\"unipaxId\","
  "\"DnaRegionReference\".\"unipaxSource\","
  "\"DnaRegionReference\".\"entityReferenceType\","
  "\"DnaRegionReference\".\"id_entityFeature\","
  "\"DnaRegionReference\".\"standardName\","
  "\"DnaRegionReference\".\"displayName\","
  "\"DnaRegionReference\".\"sequence\","
  "\"DnaRegionReference\".\"id_subRegion\","
  "\"DnaRegionReference\".\"regionType\","
  "\"DnaRegionReference\".\"organism\","
  "\"DnaRegionReference\".\"id_absoluteRegion\""
  " FROM \"DnaRegionReference\""
  " LEFT JOIN \"ImportSource\" \"unipaxSource\" ON \"unipaxSource\".\"unipaxId\" = \"DnaRegionReference\".\"unipaxSource\""
  " LEFT JOIN \"EntityReferenceTypeVocabulary\" \"entityReferenceType\" ON \"entityReferenceType\".\"unipaxId\" = \"DnaRegionReference\".\"entityReferenceType\""
  " LEFT JOIN \"SequenceRegionVocabulary" \"regionType\" ON \"regionType\".\"unipaxId\" = \"DnaRegionReference\".\"regionType\""
  " LEFT JOIN \"BioSource\" \"organism\" ON \"organism\".\"unipaxId\" = \"DnaRegionReference\".\"organism\""
  " ";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::erase_query_statement[] =
  "DELETE FROM \"DnaRegionReference\""
  " ";

  const char access::object_traits< ::UniPAX::DnaRegionReference >::table_name[] =
  "\"DnaRegionReference\"";

  void access::object_traits< ::UniPAX::DnaRegionReference >::
  persist (database&, const object_type& obj)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());
    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    id_image_type& i (sts.id_image ());
    init (i, obj.unipaxId);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    comment_traits::persist (
      obj.comment,
      idb,
      sts.container_statment_cache ().comment);

    id_memberEntityReferences_traits::persist (
      obj.id_memberEntityReferences,
      idb,
      sts.container_statment_cache ().id_memberEntityReferences);

    evidence_traits::persist (
      obj.evidence,
      idb,
      sts.container_statment_cache ().evidence);

    id_xref_traits::persist (
      obj.id_xref,
      idb,
      sts.container_statment_cache ().id_xref);

    name_traits::persist (
      obj.name,
      idb,
      sts.container_statment_cache ().name);
  }

  void access::object_traits< ::UniPAX::DnaRegionReference >::
  update (database&, const object_type& obj)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, obj.unipaxId);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.update_id_image_version () || idb.version == 0)
    {
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }

      sts.update_id_image_version (i.version);

      if (!u)
        imb.version++;
    }

    if (sts.update_statement ().execute () == 0)
      throw object_not_persistent ();

    comment_traits::update (
      obj.comment,
      idb,
      sts.container_statment_cache ().comment);

    id_memberEntityReferences_traits::update (
      obj.id_memberEntityReferences,
      idb,
      sts.container_statment_cache ().id_memberEntityReferences);

    evidence_traits::update (
      obj.evidence,
      idb,
      sts.container_statment_cache ().evidence);

    id_xref_traits::update (
      obj.id_xref,
      idb,
      sts.container_statment_cache ().id_xref);

    name_traits::update (
      obj.name,
      idb,
      sts.container_statment_cache ().name);
  }

  void access::object_traits< ::UniPAX::DnaRegionReference >::
  erase (database&, const id_type& id)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    comment_traits::erase (
      idb,
      sts.container_statment_cache ().comment);

    id_memberEntityReferences_traits::erase (
      idb,
      sts.container_statment_cache ().id_memberEntityReferences);

    evidence_traits::erase (
      idb,
      sts.container_statment_cache ().evidence);

    id_xref_traits::erase (
      idb,
      sts.container_statment_cache ().id_xref);

    name_traits::erase (
      idb,
      sts.container_statment_cache ().name);

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();
  }

  access::object_traits< ::UniPAX::DnaRegionReference >::pointer_type
  access::object_traits< ::UniPAX::DnaRegionReference >::
  find (database& db, const id_type& id)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());
    object_statements< object_type >::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory< object_type, pointer_type  >::create ());
    pointer_traits< pointer_type >::guard pg (p);
    pointer_cache_traits< pointer_type >::insert_guard ig (
      pointer_cache_traits< pointer_type >::insert (db, id, p));
    object_type& obj (pointer_traits< pointer_type >::get_ref (p));

    if (l.locked ())
    {
      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), db);
      sts.find_statement ().stream_result ();
      load_ (sts, obj);
      sts.load_delayed ();
      l.unlock ();
      callback (db, obj, callback_event::post_load);
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits< ::UniPAX::DnaRegionReference >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    object_statements< object_type >::auto_lock l (sts);

    if (!find_ (sts, id))
      return false;

    reference_cache_traits< object_type >::insert_guard ig (
      reference_cache_traits< object_type >::insert (db, id, obj));

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), db);
    sts.find_statement ().stream_result ();
    load_ (sts, obj);
    sts.load_delayed ();
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    ig.release ();
    return true;
  }

  bool access::object_traits< ::UniPAX::DnaRegionReference >::
  reload (database& db, object_type& obj)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    object_statements< object_type >::auto_lock l (sts);

    if (!find_ (sts, obj.unipaxId))
      return false;

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), db);
    sts.find_statement ().stream_result ();
    load_ (sts, obj);
    sts.load_delayed ();
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits< ::UniPAX::DnaRegionReference >::
  find_ (oracle::object_statements< object_type >& sts, const id_type& id)
  {
    using namespace oracle;

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());
    st.execute ();
    select_statement::result r (st.fetch ());
    st.free_result ();
    return r != select_statement::no_data;
  }

  void access::object_traits< ::UniPAX::DnaRegionReference >::
  load_ (oracle::object_statements< object_type >& sts, object_type& obj)
  {
    oracle::binding& idb (sts.id_image_binding ());

    comment_traits::load (
      obj.comment,
      idb,
      sts.container_statment_cache ().comment);

    id_memberEntityReferences_traits::load (
      obj.id_memberEntityReferences,
      idb,
      sts.container_statment_cache ().id_memberEntityReferences);

    evidence_traits::load (
      obj.evidence,
      idb,
      sts.container_statment_cache ().evidence);

    id_xref_traits::load (
      obj.id_xref,
      idb,
      sts.container_statment_cache ().id_xref);

    name_traits::load (
      obj.name,
      idb,
      sts.container_statment_cache ().name);
  }

  result< access::object_traits< ::UniPAX::DnaRegionReference >::object_type >
  access::object_traits< ::UniPAX::DnaRegionReference >::
  query (database&, const query_base_type& q)
  {
    using namespace oracle;
    using odb::details::shared;
    using odb::details::shared_ptr;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());

    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement + q.clause (),
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) oracle::object_result_impl<object_type> (
        q, st, sts));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits< ::UniPAX::DnaRegionReference >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace oracle;

    oracle::connection& conn (
      oracle::transaction::current ().connection ());

    delete_statement st (
      conn,
      erase_query_statement + q.clause (),
      q.parameters_binding ());

    return st.execute ();
  }
}

// Begin epilogue.
//
//
// End epilogue.

#include <odb/post.hxx>
