// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include <UNIPAX/PERSISTENCE/MYSQL/EXT/Model-odb.hxx>

#include <cassert>
#include <cstring>  // std::memcpy
#include <typeinfo>

#include <odb/polymorphic-map.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/polymorphic-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/polymorphic-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // Model
  //

  struct access::object_traits_impl< ::UniPAX::Model, id_mysql >::extra_statement_cache_type
  {
    mysql::container_statements_impl< functionDefinition_traits > functionDefinition;
    mysql::container_statements_impl< unitDefinition_traits > unitDefinition;
    mysql::container_statements_impl< parameter_traits > parameter;
    mysql::container_statements_impl< initialAssignment_traits > initialAssignment;
    mysql::container_statements_impl< rule_traits > rule;
    mysql::container_statements_impl< constraint_traits > constraint;
    mysql::container_statements_impl< event_traits > event;

    extra_statement_cache_type (
      mysql::connection& c,
      image_type&,
      id_image_type&,
      mysql::binding& id,
      mysql::binding&)
    : functionDefinition (c, id),
      unitDefinition (c, id),
      parameter (c, id),
      initialAssignment (c, id),
      rule (c, id),
      constraint (c, id),
      event (c, id)
    {
    }
  };

  // functionDefinition
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  select_statement[] =
  "SELECT "
  "`Model_functionDefinition`.`index`, "
  "`Model_functionDefinition`.`value` "
  "FROM `Model_functionDefinition` "
  "WHERE `Model_functionDefinition`.`object_id`=? ORDER BY `Model_functionDefinition`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  insert_statement[] =
  "INSERT INTO `Model_functionDefinition` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  delete_statement[] =
  "DELETE FROM `Model_functionDefinition` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::FunctionDefinition > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::FunctionDefinition > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::functionDefinition_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  // unitDefinition
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  select_statement[] =
  "SELECT "
  "`Model_unitDefinition`.`index`, "
  "`Model_unitDefinition`.`value` "
  "FROM `Model_unitDefinition` "
  "WHERE `Model_unitDefinition`.`object_id`=? ORDER BY `Model_unitDefinition`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  insert_statement[] =
  "INSERT INTO `Model_unitDefinition` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  delete_statement[] =
  "DELETE FROM `Model_unitDefinition` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::UnitDefinition > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::UnitDefinition > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::unitDefinition_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  // parameter
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  select_statement[] =
  "SELECT "
  "`Model_parameter`.`index`, "
  "`Model_parameter`.`value` "
  "FROM `Model_parameter` "
  "WHERE `Model_parameter`.`object_id`=? ORDER BY `Model_parameter`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  insert_statement[] =
  "INSERT INTO `Model_parameter` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  delete_statement[] =
  "DELETE FROM `Model_parameter` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Parameter > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Parameter > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::parameter_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  // initialAssignment
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  select_statement[] =
  "SELECT "
  "`Model_initialAssignment`.`index`, "
  "`Model_initialAssignment`.`value` "
  "FROM `Model_initialAssignment` "
  "WHERE `Model_initialAssignment`.`object_id`=? ORDER BY `Model_initialAssignment`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  insert_statement[] =
  "INSERT INTO `Model_initialAssignment` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  delete_statement[] =
  "DELETE FROM `Model_initialAssignment` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::InitialAssignment > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::InitialAssignment > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::initialAssignment_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  // rule
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  select_statement[] =
  "SELECT "
  "`Model_rule`.`index`, "
  "`Model_rule`.`value` "
  "FROM `Model_rule` "
  "WHERE `Model_rule`.`object_id`=? ORDER BY `Model_rule`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  insert_statement[] =
  "INSERT INTO `Model_rule` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  delete_statement[] =
  "DELETE FROM `Model_rule` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Rule > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Rule > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::rule_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  // constraint
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  select_statement[] =
  "SELECT "
  "`Model_constraint`.`index`, "
  "`Model_constraint`.`value` "
  "FROM `Model_constraint` "
  "WHERE `Model_constraint`.`object_id`=? ORDER BY `Model_constraint`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  insert_statement[] =
  "INSERT INTO `Model_constraint` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  delete_statement[] =
  "DELETE FROM `Model_constraint` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Constraint > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Constraint > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::constraint_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  // event
  //

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  select_statement[] =
  "SELECT "
  "`Model_event`.`index`, "
  "`Model_event`.`value` "
  "FROM `Model_event` "
  "WHERE `Model_event`.`object_id`=? ORDER BY `Model_event`.`index`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  insert_statement[] =
  "INSERT INTO `Model_event` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  delete_statement[] =
  "DELETE FROM `Model_event` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    t[1UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Event > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.value_value, is_null, id);
        i.value_null = is_null;
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::UniPAX::Event > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.value_value,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());
    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::event_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  access::object_traits_impl< ::UniPAX::Model, id_mysql >::discriminator_type
  access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  discriminator (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    discriminator_type d;
    {
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        d,
        i.typeid_value,
        i.typeid_size,
        i.typeid_null);
    }

    return d;
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // SBase base
    //
    if (object_traits_impl< ::UniPAX::SBase, id_mysql >::grow (
          i, t + 0UL))
      grew = true;

    // typeid_
    //
    if (t[6UL])
    {
      i.typeid_value.capacity (i.typeid_size);
      grew = true;
    }

    // id
    //
    if (t[7UL])
    {
      i.id_value.capacity (i.id_size);
      grew = true;
    }

    // name
    //
    if (t[8UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // substanceUnits
    //
    if (t[9UL])
    {
      i.substanceUnits_value.capacity (i.substanceUnits_size);
      grew = true;
    }

    // timeUnits
    //
    if (t[10UL])
    {
      i.timeUnits_value.capacity (i.timeUnits_size);
      grew = true;
    }

    // volumeUnits
    //
    if (t[11UL])
    {
      i.volumeUnits_value.capacity (i.volumeUnits_size);
      grew = true;
    }

    // areaUnits
    //
    if (t[12UL])
    {
      i.areaUnits_value.capacity (i.areaUnits_size);
      grew = true;
    }

    // lengthUnits
    //
    if (t[13UL])
    {
      i.lengthUnits_value.capacity (i.lengthUnits_size);
      grew = true;
    }

    // extentUnit
    //
    if (t[14UL])
    {
      i.extentUnit_value.capacity (i.extentUnit_size);
      grew = true;
    }

    // conversionFactor
    //
    if (t[15UL])
    {
      i.conversionFactor_value.capacity (i.conversionFactor_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // SBase base
    //
    object_traits_impl< ::UniPAX::SBase, id_mysql >::bind (b + n, i, sk);
    n += sk == statement_update ? 5UL : 6UL;

    // typeid_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_STRING;
      b[n].buffer = i.typeid_value.data ();
      b[n].buffer_length = static_cast<unsigned long> (
        i.typeid_value.capacity ());
      b[n].length = &i.typeid_size;
      b[n].is_null = &i.typeid_null;
      n++;
    }

    // id
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.id_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.id_value.capacity ());
    b[n].length = &i.id_size;
    b[n].is_null = &i.id_null;
    n++;

    // name
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.name_value.capacity ());
    b[n].length = &i.name_size;
    b[n].is_null = &i.name_null;
    n++;

    // substanceUnits
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.substanceUnits_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.substanceUnits_value.capacity ());
    b[n].length = &i.substanceUnits_size;
    b[n].is_null = &i.substanceUnits_null;
    n++;

    // timeUnits
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.timeUnits_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.timeUnits_value.capacity ());
    b[n].length = &i.timeUnits_size;
    b[n].is_null = &i.timeUnits_null;
    n++;

    // volumeUnits
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.volumeUnits_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.volumeUnits_value.capacity ());
    b[n].length = &i.volumeUnits_size;
    b[n].is_null = &i.volumeUnits_null;
    n++;

    // areaUnits
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.areaUnits_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.areaUnits_value.capacity ());
    b[n].length = &i.areaUnits_size;
    b[n].is_null = &i.areaUnits_null;
    n++;

    // lengthUnits
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.lengthUnits_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.lengthUnits_value.capacity ());
    b[n].length = &i.lengthUnits_size;
    b[n].is_null = &i.lengthUnits_null;
    n++;

    // extentUnit
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.extentUnit_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.extentUnit_value.capacity ());
    b[n].length = &i.extentUnit_size;
    b[n].is_null = &i.extentUnit_null;
    n++;

    // conversionFactor
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.conversionFactor_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.conversionFactor_value.capacity ());
    b[n].length = &i.conversionFactor_size;
    b[n].is_null = &i.conversionFactor_null;
    n++;
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // SBase base
    //
    if (object_traits_impl< ::UniPAX::SBase, id_mysql >::init (i, o, sk))
      grew = true;

    // typeid_
    //
    if (sk == statement_insert)
    {
      const info_type& di (map->find (typeid (o)));

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.typeid_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.typeid_value,
        size,
        is_null,
        di.discriminator);
      i.typeid_null = is_null;
      i.typeid_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.typeid_value.capacity ());
    }

    // id
    //
    {
      ::std::string const& v =
        o.id;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        v);
      i.id_null = is_null;
      i.id_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.id_value.capacity ());
    }

    // name
    //
    {
      ::std::string const& v =
        o.name;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.name_value,
        size,
        is_null,
        v);
      i.name_null = is_null;
      i.name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.name_value.capacity ());
    }

    // substanceUnits
    //
    {
      ::std::string const& v =
        o.substanceUnits;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.substanceUnits_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.substanceUnits_value,
        size,
        is_null,
        v);
      i.substanceUnits_null = is_null;
      i.substanceUnits_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.substanceUnits_value.capacity ());
    }

    // timeUnits
    //
    {
      ::std::string const& v =
        o.timeUnits;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.timeUnits_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.timeUnits_value,
        size,
        is_null,
        v);
      i.timeUnits_null = is_null;
      i.timeUnits_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.timeUnits_value.capacity ());
    }

    // volumeUnits
    //
    {
      ::std::string const& v =
        o.volumeUnits;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.volumeUnits_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.volumeUnits_value,
        size,
        is_null,
        v);
      i.volumeUnits_null = is_null;
      i.volumeUnits_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.volumeUnits_value.capacity ());
    }

    // areaUnits
    //
    {
      ::std::string const& v =
        o.areaUnits;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.areaUnits_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.areaUnits_value,
        size,
        is_null,
        v);
      i.areaUnits_null = is_null;
      i.areaUnits_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.areaUnits_value.capacity ());
    }

    // lengthUnits
    //
    {
      ::std::string const& v =
        o.lengthUnits;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.lengthUnits_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.lengthUnits_value,
        size,
        is_null,
        v);
      i.lengthUnits_null = is_null;
      i.lengthUnits_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.lengthUnits_value.capacity ());
    }

    // extentUnit
    //
    {
      ::std::string const& v =
        o.extentUnit;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.extentUnit_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.extentUnit_value,
        size,
        is_null,
        v);
      i.extentUnit_null = is_null;
      i.extentUnit_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.extentUnit_value.capacity ());
    }

    // conversionFactor
    //
    {
      ::std::string const& v =
        o.conversionFactor;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.conversionFactor_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.conversionFactor_value,
        size,
        is_null,
        v);
      i.conversionFactor_null = is_null;
      i.conversionFactor_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.conversionFactor_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // SBase base
    //
    object_traits_impl< ::UniPAX::SBase, id_mysql >::init (o, i, db);

    // id
    //
    {
      ::std::string& v =
        o.id;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.id_value,
        i.id_size,
        i.id_null);
    }

    // name
    //
    {
      ::std::string& v =
        o.name;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // substanceUnits
    //
    {
      ::std::string& v =
        o.substanceUnits;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.substanceUnits_value,
        i.substanceUnits_size,
        i.substanceUnits_null);
    }

    // timeUnits
    //
    {
      ::std::string& v =
        o.timeUnits;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.timeUnits_value,
        i.timeUnits_size,
        i.timeUnits_null);
    }

    // volumeUnits
    //
    {
      ::std::string& v =
        o.volumeUnits;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.volumeUnits_value,
        i.volumeUnits_size,
        i.volumeUnits_null);
    }

    // areaUnits
    //
    {
      ::std::string& v =
        o.areaUnits;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.areaUnits_value,
        i.areaUnits_size,
        i.areaUnits_null);
    }

    // lengthUnits
    //
    {
      ::std::string& v =
        o.lengthUnits;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.lengthUnits_value,
        i.lengthUnits_size,
        i.lengthUnits_null);
    }

    // extentUnit
    //
    {
      ::std::string& v =
        o.extentUnit;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.extentUnit_value,
        i.extentUnit_size,
        i.extentUnit_null);
    }

    // conversionFactor
    //
    {
      ::std::string& v =
        o.conversionFactor;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.conversionFactor_value,
        i.conversionFactor_size,
        i.conversionFactor_null);
    }
  }

  access::object_traits_impl< ::UniPAX::Model, id_mysql >::map_type*
  access::object_traits_impl< ::UniPAX::Model, id_mysql >::map;

  const access::object_traits_impl< ::UniPAX::Model, id_mysql >::info_type
  access::object_traits_impl< ::UniPAX::Model, id_mysql >::info (
    typeid (::UniPAX::Model),
    0,
    0,
    "UniPAX::Model",
    &odb::create_impl< ::UniPAX::Model >,
    &odb::dispatch_impl< ::UniPAX::Model, id_mysql >,
    0);

  static const access::object_traits_impl< ::UniPAX::Model, id_mysql >::entry_type
  polymorphic_entry_for_UniPAX_Model;

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::persist_statement[] =
  "INSERT INTO `Model` "
  "(`unipaxId`, "
  "`unipaxSource`, "
  "`metaId`, "
  "`sboTerm`, "
  "`notes`, "
  "`annotation`, "
  "`typeid`, "
  "`id`, "
  "`name`, "
  "`substanceUnits`, "
  "`timeUnits`, "
  "`volumeUnits`, "
  "`areaUnits`, "
  "`lengthUnits`, "
  "`extentUnit`, "
  "`conversionFactor`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::find_statement[] =
  "SELECT "
  "`Model`.`unipaxId`, "
  "`Model`.`unipaxSource`, "
  "`Model`.`metaId`, "
  "`Model`.`sboTerm`, "
  "`Model`.`notes`, "
  "`Model`.`annotation`, "
  "`Model`.`typeid`, "
  "`Model`.`id`, "
  "`Model`.`name`, "
  "`Model`.`substanceUnits`, "
  "`Model`.`timeUnits`, "
  "`Model`.`volumeUnits`, "
  "`Model`.`areaUnits`, "
  "`Model`.`lengthUnits`, "
  "`Model`.`extentUnit`, "
  "`Model`.`conversionFactor` "
  "FROM `Model` "
  "WHERE `Model`.`unipaxId`=?";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  find_discriminator_statement[] =
  "SELECT "
  "`Model`.`typeid` "
  "FROM `Model` "
  "WHERE `Model`.`unipaxId`=?";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::update_statement[] =
  "UPDATE `Model` "
  "SET "
  "`unipaxSource`=?, "
  "`metaId`=?, "
  "`sboTerm`=?, "
  "`notes`=?, "
  "`annotation`=?, "
  "`id`=?, "
  "`name`=?, "
  "`substanceUnits`=?, "
  "`timeUnits`=?, "
  "`volumeUnits`=?, "
  "`areaUnits`=?, "
  "`lengthUnits`=?, "
  "`extentUnit`=?, "
  "`conversionFactor`=? "
  "WHERE `unipaxId`=?";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::erase_statement[] =
  "DELETE FROM `Model` "
  "WHERE `unipaxId`=?";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::query_statement[] =
  "SELECT\n"
  "`Model`.`unipaxId`,\n"
  "`Model`.`unipaxSource`,\n"
  "`Model`.`metaId`,\n"
  "`Model`.`sboTerm`,\n"
  "`Model`.`notes`,\n"
  "`Model`.`annotation`,\n"
  "`Model`.`typeid`,\n"
  "`Model`.`id`,\n"
  "`Model`.`name`,\n"
  "`Model`.`substanceUnits`,\n"
  "`Model`.`timeUnits`,\n"
  "`Model`.`volumeUnits`,\n"
  "`Model`.`areaUnits`,\n"
  "`Model`.`lengthUnits`,\n"
  "`Model`.`extentUnit`,\n"
  "`Model`.`conversionFactor`\n"
  "FROM `Model`\n"
  "LEFT JOIN `ImportSource` AS `unipaxSource_ImportSource` ON `unipaxSource_ImportSource`.`unipaxId`=`Model`.`unipaxSource`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::erase_query_statement[] =
  "DELETE FROM `Model`";

  const char access::object_traits_impl< ::UniPAX::Model, id_mysql >::table_name[] =
  "`Model`";

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  persist (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    using namespace mysql;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_persist, db, &obj, 0);
        return;
      }
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (top)
      callback (db,
                obj,
                callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    id_image_type& i (sts.id_image ());
    init (i, obj.unipaxId);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // functionDefinition
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::FunctionDefinition > > const& v =
        obj.functionDefinition;

      functionDefinition_traits::persist (
        v,
        esc.functionDefinition);
    }

    // unitDefinition
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::UnitDefinition > > const& v =
        obj.unitDefinition;

      unitDefinition_traits::persist (
        v,
        esc.unitDefinition);
    }

    // parameter
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Parameter > > const& v =
        obj.parameter;

      parameter_traits::persist (
        v,
        esc.parameter);
    }

    // initialAssignment
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::InitialAssignment > > const& v =
        obj.initialAssignment;

      initialAssignment_traits::persist (
        v,
        esc.initialAssignment);
    }

    // rule
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Rule > > const& v =
        obj.rule;

      rule_traits::persist (
        v,
        esc.rule);
    }

    // constraint
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Constraint > > const& v =
        obj.constraint;

      constraint_traits::persist (
        v,
        esc.constraint);
    }

    // event
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Event > > const& v =
        obj.event;

      event_traits::persist (
        v,
        esc.event);
    }

    if (top)
      callback (db,
                obj,
                callback_event::post_persist);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  update (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    using namespace mysql;
    using mysql::update_statement;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_update, db, &obj, 0);
        return;
      }
    }

    if (top)
      callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.unipaxId);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // functionDefinition
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::FunctionDefinition > > const& v =
        obj.functionDefinition;

      functionDefinition_traits::update (
        v,
        esc.functionDefinition);
    }

    // unitDefinition
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::UnitDefinition > > const& v =
        obj.unitDefinition;

      unitDefinition_traits::update (
        v,
        esc.unitDefinition);
    }

    // parameter
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Parameter > > const& v =
        obj.parameter;

      parameter_traits::update (
        v,
        esc.parameter);
    }

    // initialAssignment
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::InitialAssignment > > const& v =
        obj.initialAssignment;

      initialAssignment_traits::update (
        v,
        esc.initialAssignment);
    }

    // rule
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Rule > > const& v =
        obj.rule;

      rule_traits::update (
        v,
        esc.rule);
    }

    // constraint
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Constraint > > const& v =
        obj.constraint;

      constraint_traits::update (
        v,
        esc.constraint);
    }

    // event
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Event > > const& v =
        obj.event;

      event_traits::update (
        v,
        esc.event);
    }

    if (top)
    {
      callback (db, obj, callback_event::post_update);
      pointer_cache_traits::update (db, obj);
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  erase (database& db, const id_type& id, bool top, bool dyn)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (dyn)
    {
      discriminator_type d;
      root_traits::discriminator_ (sts.root_statements (), id, &d);

      if (d != info.discriminator)
      {
        const info_type& pi (root_traits::map->find (d));

        if (!pi.derived (info))
          throw object_not_persistent ();

        pi.dispatch (info_type::call_erase, db, 0, &id);
        return;
      }
    }

    if (top)
    {
      id_image_type& i (sts.id_image ());
      init (i, id);

      binding& idb (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // functionDefinition
    //
    functionDefinition_traits::erase (
      esc.functionDefinition);

    // unitDefinition
    //
    unitDefinition_traits::erase (
      esc.unitDefinition);

    // parameter
    //
    parameter_traits::erase (
      esc.parameter);

    // initialAssignment
    //
    initialAssignment_traits::erase (
      esc.initialAssignment);

    // rule
    //
    rule_traits::erase (
      esc.rule);

    // constraint
    //
    constraint_traits::erase (
      esc.constraint);

    // event
    //
    event_traits::erase (
      esc.event);

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    if (top)
      pointer_cache_traits::erase (db, id);
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  erase (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_erase, db, &obj, 0);
        return;
      }
    }

    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj), true, false);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::UniPAX::Model, id_mysql >::pointer_type
  access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    root_traits::discriminator_type d;

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
      d = root_traits::discriminator (sts.image ());
    }
    else
      root_traits::discriminator_ (sts, id, &d);

    const info_type& pi (
      d == info.discriminator ? info : root_traits::map->find (d));

    pointer_type p (pi.create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback_event ce (callback_event::pre_load);
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);

      if (&pi != &info)
      {
        std::size_t d (depth);
        pi.dispatch (info_type::call_load, db, &obj, &d);
      }

      sts.load_delayed (0);
      l.unlock ();
      ce = callback_event::post_load;
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position (), pi.delayed_loader);

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  find (database& db, const id_type& id, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace mysql;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        return pi.dispatch (info_type::call_find, db, &obj, &id);
      }
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  reload (database& db, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace mysql;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        return pi.dispatch (info_type::call_reload, db, &obj, 0);
      }
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.unipaxId);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // functionDefinition
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::FunctionDefinition > >& v =
        obj.functionDefinition;

      functionDefinition_traits::load (
        v,
        esc.functionDefinition);
    }

    // unitDefinition
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::UnitDefinition > >& v =
        obj.unitDefinition;

      unitDefinition_traits::load (
        v,
        esc.unitDefinition);
    }

    // parameter
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Parameter > >& v =
        obj.parameter;

      parameter_traits::load (
        v,
        esc.parameter);
    }

    // initialAssignment
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::InitialAssignment > >& v =
        obj.initialAssignment;

      initialAssignment_traits::load (
        v,
        esc.initialAssignment);
    }

    // rule
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Rule > >& v =
        obj.rule;

      rule_traits::load (
        v,
        esc.rule);
    }

    // constraint
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Constraint > >& v =
        obj.constraint;

      constraint_traits::load (
        v,
        esc.constraint);
    }

    // event
    //
    {
      ::std::vector< ::boost::shared_ptr< ::UniPAX::Event > >& v =
        obj.event;

      event_traits::load (
        v,
        esc.event);
    }
  }

  void access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  discriminator_ (statements_type& sts,
                  const id_type& id,
                  discriminator_type* pd)
  {
    using namespace mysql;

    id_image_type& idi (sts.discriminator_id_image ());
    init (idi, id);

    binding& idb (sts.discriminator_id_image_binding ());
    if (idi.version != sts.discriminator_id_image_version () ||
        idb.version == 0)
    {
      bind (idb.bind, idi);
      sts.discriminator_id_image_version (idi.version);
      idb.version++;
    }

    discriminator_image_type& i (sts.discriminator_image ());
    binding& imb (sts.discriminator_image_binding ());

    if (i.version != sts.discriminator_image_version () ||
        imb.version == 0)
    {
      MYSQL_BIND* b (imb.bind);
      std::size_t n (0);
      {
        b[n].buffer_type = MYSQL_TYPE_STRING;
        b[n].buffer = i.discriminator_value.data ();
        b[n].buffer_length = static_cast<unsigned long> (
          i.discriminator_value.capacity ());
        b[n].length = &i.discriminator_size;
        b[n].is_null = &i.discriminator_null;
      }

      sts.discriminator_image_version (i.version);
      imb.version++;
    }

    {
      select_statement& st (sts.find_discriminator_statement ());
      st.execute ();
      auto_result ar (st);
      select_statement::result r (st.fetch ());

      if (r == select_statement::no_data)
      {
        throw object_not_persistent ();
      }
      else if (r == select_statement::truncated)
      {
        bool grew (false);
        my_bool* t (sts.discriminator_image_truncated ());

        if (t[0UL])
        {
          i.discriminator_value.capacity (i.discriminator_size);
          grew = true;
        }

        if (grew)
          i.version++;

        if (i.version != sts.discriminator_image_version ())
        {
          MYSQL_BIND* b (imb.bind);
          std::size_t n (0);
          {
            b[n].buffer_type = MYSQL_TYPE_STRING;
            b[n].buffer = i.discriminator_value.data ();
            b[n].buffer_length = static_cast<unsigned long> (
              i.discriminator_value.capacity ());
            b[n].length = &i.discriminator_size;
            b[n].is_null = &i.discriminator_null;
          }

          sts.discriminator_image_version (i.version);
          imb.version++;
          st.refetch ();
        }
      }
    }

    if (pd != 0)
    {
      discriminator_type& d (*pd);
      {
        mysql::value_traits<
            ::std::string,
            mysql::id_string >::set_value (
          d,
          i.discriminator_value,
          i.discriminator_size,
          i.discriminator_null);
      }
    }
  }

  result< access::object_traits_impl< ::UniPAX::Model, id_mysql >::object_type >
  access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::polymorphic_object_result_impl<object_type> > r (
      new (shared) mysql::polymorphic_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::UniPAX::Model, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
