### list all filenames of the directory here ###
SET(GROUP IMPORT)

INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/IMPORT/BIOPAX/sources.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/IMPORT/SBML/sources.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/IMPORT/GENESET/sources.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/IMPORT/TFENCYCLOPEDIA/sources.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/IMPORT/GRAPHML/sources.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/IMPORT/MZTAB/sources.cmake)

SET(DIRECTORY "${CMAKE_SOURCE_DIR}/include/UNIPAX/${GROUP}")

FILE(GLOB HEADERS_LIST "${DIRECTORY}/*.h")

ADD_UNIPAX_HEADERS("${GROUP}" "${HEADERS_LIST}")
