/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Event_eventAssignment`;

DROP TABLE IF EXISTS `Event`;

CREATE TABLE `Event` (
  `unipaxId` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `unipaxSource` BIGINT UNSIGNED NULL,
  `metaId` TEXT NOT NULL,
  `sboTerm` TEXT NOT NULL,
  `notes` TEXT NOT NULL,
  `annotation` TEXT NOT NULL,
  `typeid` VARCHAR(255) NOT NULL,
  `useValuesFromTriggerTime` TINYINT(1) NOT NULL,
  `id` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `priority` BIGINT UNSIGNED NULL,
  `delay` BIGINT UNSIGNED NULL,
  `trigger` BIGINT UNSIGNED NULL)
 ENGINE=InnoDB;

CREATE TABLE `Event_eventAssignment` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NULL,
  CONSTRAINT `Event_eventAssignment_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Event` (`unipaxId`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Event_eventAssignment` (`object_id`);

CREATE INDEX `index_i`
  ON `Event_eventAssignment` (`index`);

/*
ALTER TABLE `Event`
  ADD CONSTRAINT `Event_unipaxSource_fk`
    FOREIGN KEY (`unipaxSource`)
    REFERENCES `ImportSource` (`unipaxId`),
  ADD CONSTRAINT `Event_priority_fk`
    FOREIGN KEY (`priority`)
    REFERENCES `Priority` (`unipaxId`),
  ADD CONSTRAINT `Event_delay_fk`
    FOREIGN KEY (`delay`)
    REFERENCES `Delay` (`unipaxId`),
  ADD CONSTRAINT `Event_trigger_fk`
    FOREIGN KEY (`trigger`)
    REFERENCES `Trigger` (`unipaxId`)
*/

/*
ALTER TABLE `Event_eventAssignment`
  ADD CONSTRAINT `Event_eventAssignment_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `EventAssignment` (`unipaxId`)
*/

