/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `ImportSource`;

CREATE TABLE `ImportSource` (
  `unipaxId` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `typeid` VARCHAR(255) NOT NULL,
  `name` TEXT NOT NULL,
  `version` TEXT NOT NULL,
  `successor` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `ImportSource_successor_fk`
    FOREIGN KEY (`successor`)
    REFERENCES `ImportSource` (`unipaxId`)
  */)
 ENGINE=InnoDB;

