/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Parameter`;

CREATE TABLE `Parameter` (
  `unipaxId` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `unipaxSource` BIGINT UNSIGNED NULL,
  `metaId` TEXT NOT NULL,
  `sboTerm` TEXT NOT NULL,
  `notes` TEXT NOT NULL,
  `annotation` TEXT NOT NULL,
  `typeid` VARCHAR(255) NOT NULL,
  `constant` TINYINT(1) NOT NULL,
  `id` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `value` DOUBLE NOT NULL,
  `units` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `Parameter`
  ADD CONSTRAINT `Parameter_unipaxSource_fk`
    FOREIGN KEY (`unipaxSource`)
    REFERENCES `ImportSource` (`unipaxId`)
*/

