### list all filenames of the directory here ###
SET(GROUP GRAPH)

SET(DIRECTORY "${CMAKE_SOURCE_DIR}/include/UNIPAX/${GROUP}")

FILE(GLOB HEADERS_LIST "${DIRECTORY}/*.h")	

ADD_UNIPAX_HEADERS("${GROUP}" "${HEADERS_LIST}")

INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/GRAPH/LEMON/sources.cmake)
INCLUDE(${CMAKE_SOURCE_DIR}/include/UNIPAX/GRAPH/MAPPING/sources.cmake)


