MACRO(UNIPAX_ADD_TESTS GROUP)
	SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/Test/${GROUP}")

	FOREACH(source ${ARGN})
		STRING(REPLACE ".cpp" "" exec ${source})
		ADD_EXECUTABLE(${exec} ${GROUP}/${source})
		TARGET_LINK_LIBRARIES(${exec} ${TEST_REQUIRED_LIBRARIES})
		ADD_TEST(NAME ${exec} COMMAND ${exec})
		LIST(APPEND TEST_EXECUTABLES ${exec})
	ENDFOREACH()

ENDMACRO()
