/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

SET FEEDBACK OFF;
WHENEVER SQLERROR EXIT FAILURE;
WHENEVER OSERROR EXIT FAILURE;

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "BioSource_name" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "BioSource_name_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "BioSource_name_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "BioSource_id_xref" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "BioSource_id_xref_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "BioSource_id_xref_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "BioSource_cellType" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "BioSource_cellType_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "BioSource_cellType_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "BioSource_comment" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "BioSource_comment_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "BioSource_comment_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "BioSource" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "BioSource_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "BioSource_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/


CREATE TABLE "BioSource" (
  "unipaxId" NUMBER(20) NOT NULL PRIMARY KEY,
  "unipaxSource" NUMBER(20),
  "tissue" NUMBER(20),
  "standardName" VARCHAR2(512),
  "displayName" VARCHAR2(512));

CREATE TABLE "BioSource_comment" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" VARCHAR2(512),
  CONSTRAINT "BioSource_comment_object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "BioSource" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "BioSource_comment_object_id_i"
  ON "BioSource_comment" ("object_id");

CREATE INDEX "BioSource_comment_index_i"
  ON "BioSource_comment" ("index");

CREATE TABLE "BioSource_cellType" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" NUMBER(20),
  CONSTRAINT "BioSource_cellType_object_id_f"
    FOREIGN KEY ("object_id")
    REFERENCES "BioSource" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "BioSource_cellType_object_id_i"
  ON "BioSource_cellType" ("object_id");

CREATE INDEX "BioSource_cellType_index_i"
  ON "BioSource_cellType" ("index");

CREATE TABLE "BioSource_id_xref" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" NUMBER(20) NOT NULL,
  CONSTRAINT "BioSource_id_xref_object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "BioSource" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "BioSource_id_xref_object_id_i"
  ON "BioSource_id_xref" ("object_id");

CREATE INDEX "BioSource_id_xref_index_i"
  ON "BioSource_id_xref" ("index");

CREATE TABLE "BioSource_name" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" VARCHAR2(512),
  CONSTRAINT "BioSource_name_object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "BioSource" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "BioSource_name_object_id_i"
  ON "BioSource_name" ("object_id");

CREATE INDEX "BioSource_name_index_i"
  ON "BioSource_name" ("index");

ALTER TABLE "BioSource" ADD
  CONSTRAINT "BioSource_unipaxSource_fk"
    FOREIGN KEY ("unipaxSource")
    REFERENCES "ImportSource" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BioSource" ADD
  CONSTRAINT "BioSource_tissue_fk"
    FOREIGN KEY ("tissue")
    REFERENCES "TissueVocabulary" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BioSource_cellType" ADD
  CONSTRAINT "BioSource_cellType_value_fk"
    FOREIGN KEY ("value")
    REFERENCES "CellVocabulary" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

EXIT;
