// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ENTITY_REFERENCE_ODB_HXX
#define ENTITY_REFERENCE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 10800UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 1080000 // 1.8.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
//
// End prologue.

#include <UNIPAX/KERNEL/BIOPAX/EntityReference.h>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/ControlledVocabulary-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/Entity-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/EntityFeature-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/EntityReferenceTypeVocabulary-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/Evidence-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/EvidenceCodeVocabulary-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/ExperimentalForm-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/ExperimentalFormVocabulary-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/Provenance-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/Score-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/SequenceLocation-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/SequenceRegionVocabulary-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/Thing-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/UtilityClass-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/Xref-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/EXT/ImportSource-odb.hxx>

#include <UNIPAX/PERSISTENCE/ORACLE/EXT/UPBase-odb.hxx>

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/result.hxx>

#include <odb/details/buffer.hxx>
#include <odb/details/unused.hxx>

#include <odb/oracle/version.hxx>
#include <odb/oracle/forward.hxx>
#include <odb/oracle/oracle-types.hxx>
#include <odb/oracle/query.hxx>

namespace odb
{
  // EntityReference
  //
  template <>
  struct class_traits< ::UniPAX::EntityReference >
  {
    static const class_kind kind = class_object;
  };

  template <const char* table>
  struct pointer_query_columns< ::UniPAX::EntityReference, table >: pointer_query_columns< ::UniPAX::UtilityClass, table >
  {
    // UtilityClass
    //
    typedef pointer_query_columns< ::UniPAX::UtilityClass, table > UtilityClass;

    // entityReferenceType
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        long long unsigned int,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    entityReferenceType_type_;

    static const entityReferenceType_type_ entityReferenceType;

    // id_entityFeature
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        long long unsigned int,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    id_entityFeature_type_;

    static const id_entityFeature_type_ id_entityFeature;

    // standardName
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::std::string,
        oracle::id_string >::query_type,
      oracle::id_string >
    standardName_type_;

    static const standardName_type_ standardName;

    // displayName
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::std::string,
        oracle::id_string >::query_type,
      oracle::id_string >
    displayName_type_;

    static const displayName_type_ displayName;
  };

  template <const char* table>
  const typename pointer_query_columns< ::UniPAX::EntityReference, table >::entityReferenceType_type_
  pointer_query_columns< ::UniPAX::EntityReference, table >::entityReferenceType (table, "\"entityReferenceType\"", 20);

  template <const char* table>
  const typename pointer_query_columns< ::UniPAX::EntityReference, table >::id_entityFeature_type_
  pointer_query_columns< ::UniPAX::EntityReference, table >::id_entityFeature (table, "\"id_entityFeature\"", 20);

  template <const char* table>
  const typename pointer_query_columns< ::UniPAX::EntityReference, table >::standardName_type_
  pointer_query_columns< ::UniPAX::EntityReference, table >::standardName (table, "\"standardName\"", 512);

  template <const char* table>
  const typename pointer_query_columns< ::UniPAX::EntityReference, table >::displayName_type_
  pointer_query_columns< ::UniPAX::EntityReference, table >::displayName (table, "\"displayName\"", 512);

  template <>
  class access::object_traits< ::UniPAX::EntityReference >
  {
    public:
    typedef ::UniPAX::EntityReference object_type;
    typedef ::boost::shared_ptr< ::UniPAX::EntityReference > pointer_type;
    typedef object_traits< ::UniPAX::UPBase >::id_type id_type;

    static const bool auto_id = object_traits< ::UniPAX::UPBase >::auto_id;

    typedef object_traits< ::UniPAX::UPBase >::id_image_type id_image_type;

    struct image_type: object_traits< ::UniPAX::UtilityClass >::image_type
    {
      // entityReferenceType
      //
      char entityReferenceType_value[12];
      ub2 entityReferenceType_size;
      sb2 entityReferenceType_indicator;

      // id_entityFeature
      //
      char id_entityFeature_value[12];
      ub2 id_entityFeature_size;
      sb2 id_entityFeature_indicator;

      // standardName
      //
      char standardName_value[512];
      ub2 standardName_size;
      sb2 standardName_indicator;

      // displayName
      //
      char displayName_value[512];
      ub2 displayName_size;
      sb2 displayName_indicator;

      std::size_t version;

      oracle::change_callback change_callback_;

      oracle::change_callback*
      change_callback ()
      {
        return &change_callback_;
      }
    };

    // comment
    //
    struct comment_traits: access::object_traits< ::UniPAX::UtilityClass >::comment_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t cond_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const char insert_one_statement[];
      static const char select_all_statement[];
      static const char delete_all_statement[];
    };

    // id_memberEntityReferences
    //
    struct id_memberEntityReferences_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t cond_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const char insert_one_statement[];
      static const char select_all_statement[];
      static const char delete_all_statement[];

      typedef ::std::vector< long long unsigned int > container_type;
      typedef odb::access::container_traits< container_type > container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef oracle::container_statements< id_memberEntityReferences_traits > statements_type;

      struct cond_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        std::size_t version;
      };

      struct data_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        // value
        //
        char value_value[12];
        ub2 value_size;
        sb2 value_indicator;

        std::size_t version;
      };

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            cond_image_type&);

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      init (data_image_type&, index_type, const value_type&);

      static void
      init (index_type&, value_type&, const data_image_type&, database&);

      static void
      insert_one (index_type, const value_type&, void*);

      static bool
      load_all (index_type&, value_type&, void*);

      static void
      delete_all (void*);

      static void
      persist (const container_type&,
               const oracle::binding& id,
               statements_type&);

      static void
      load (container_type&,
            const oracle::binding& id,
            statements_type&);

      static void
      update (const container_type&,
              const oracle::binding& id,
              statements_type&);

      static void
      erase (const oracle::binding& id, statements_type&);
    };

    // evidence
    //
    struct evidence_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t cond_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const char insert_one_statement[];
      static const char select_all_statement[];
      static const char delete_all_statement[];

      typedef ::std::vector< ::boost::shared_ptr< ::UniPAX::Evidence > > container_type;
      typedef odb::access::container_traits< container_type > container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef oracle::container_statements< evidence_traits > statements_type;

      struct cond_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        std::size_t version;
      };

      struct data_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        // value
        //
        char value_value[12];
        ub2 value_size;
        sb2 value_indicator;

        std::size_t version;
      };

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            cond_image_type&);

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      init (data_image_type&, index_type, const value_type&);

      static void
      init (index_type&, value_type&, const data_image_type&, database&);

      static void
      insert_one (index_type, const value_type&, void*);

      static bool
      load_all (index_type&, value_type&, void*);

      static void
      delete_all (void*);

      static void
      persist (const container_type&,
               const oracle::binding& id,
               statements_type&);

      static void
      load (container_type&,
            const oracle::binding& id,
            statements_type&);

      static void
      update (const container_type&,
              const oracle::binding& id,
              statements_type&);

      static void
      erase (const oracle::binding& id, statements_type&);
    };

    // id_xref
    //
    struct id_xref_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t cond_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const char insert_one_statement[];
      static const char select_all_statement[];
      static const char delete_all_statement[];

      typedef ::std::vector< long long unsigned int > container_type;
      typedef odb::access::container_traits< container_type > container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef oracle::container_statements< id_xref_traits > statements_type;

      struct cond_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        std::size_t version;
      };

      struct data_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        // value
        //
        char value_value[12];
        ub2 value_size;
        sb2 value_indicator;

        std::size_t version;
      };

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            cond_image_type&);

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      init (data_image_type&, index_type, const value_type&);

      static void
      init (index_type&, value_type&, const data_image_type&, database&);

      static void
      insert_one (index_type, const value_type&, void*);

      static bool
      load_all (index_type&, value_type&, void*);

      static void
      delete_all (void*);

      static void
      persist (const container_type&,
               const oracle::binding& id,
               statements_type&);

      static void
      load (container_type&,
            const oracle::binding& id,
            statements_type&);

      static void
      update (const container_type&,
              const oracle::binding& id,
              statements_type&);

      static void
      erase (const oracle::binding& id, statements_type&);
    };

    // name
    //
    struct name_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t cond_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const char insert_one_statement[];
      static const char select_all_statement[];
      static const char delete_all_statement[];

      typedef ::std::vector< ::std::basic_string< char > > container_type;
      typedef odb::access::container_traits< container_type > container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef oracle::container_statements< name_traits > statements_type;

      struct cond_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        std::size_t version;
      };

      struct data_image_type
      {
        // index
        //
        char index_value[12];
        ub2 index_size;
        sb2 index_indicator;

        // value
        //
        char value_value[512];
        ub2 value_size;
        sb2 value_indicator;

        std::size_t version;
      };

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            cond_image_type&);

      static void
      bind (oracle::bind*,
            const oracle::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      init (data_image_type&, index_type, const value_type&);

      static void
      init (index_type&, value_type&, const data_image_type&, database&);

      static void
      insert_one (index_type, const value_type&, void*);

      static bool
      load_all (index_type&, value_type&, void*);

      static void
      delete_all (void*);

      static void
      persist (const container_type&,
               const oracle::binding& id,
               statements_type&);

      static void
      load (container_type&,
            const oracle::binding& id,
            statements_type&);

      static void
      update (const container_type&,
              const oracle::binding& id,
              statements_type&);

      static void
      erase (const oracle::binding& id, statements_type&);
    };

    static id_type
    id (const object_type&);

    static id_type
    id (const image_type&);

    static void
    bind (oracle::bind*, image_type&, oracle::statement_kind);

    static void
    bind (oracle::bind*, id_image_type&);

    static bool
    init (image_type&, const object_type&, oracle::statement_kind);

    static void
    init (object_type&, const image_type&, database&);

    static void
    init (id_image_type&, const id_type&);

    typedef oracle::query query_base_type;

    struct query_type;
    struct container_statement_cache_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (oracle::object_statements< object_type >&, const id_type&);

    static void
    load_ (oracle::object_statements< object_type >&, object_type&);
  };

  // EntityReference
  //
  template <>
  struct query_columns_base< ::UniPAX::EntityReference >
  {
    // entityReferenceType
    //
    static const char entityReferenceType_alias_[];
  };

  template <const char* table>
  struct query_columns< ::UniPAX::EntityReference, table >:
    query_columns_base< ::UniPAX::EntityReference >,
    query_columns< ::UniPAX::UtilityClass, table >
  {
    // UtilityClass
    //
    typedef query_columns< ::UniPAX::UtilityClass, table > UtilityClass;

    // entityReferenceType
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        long long unsigned int,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    entityReferenceType_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::UniPAX::EntityReferenceTypeVocabulary,
        entityReferenceType_alias_ > >
    entityReferenceType_pointer_type_;

    struct entityReferenceType_type_: entityReferenceType_pointer_type_, entityReferenceType_column_type_
    {
      entityReferenceType_type_ (const char* t,
                                 const char* c,
                                 unsigned short p = 0xFFF,
                                 short s = 0xFFF)
        : entityReferenceType_column_type_ (t, c, p, s)
      {
      }
    };

    static const entityReferenceType_type_ entityReferenceType;

    // id_entityFeature
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        long long unsigned int,
        oracle::id_big_int >::query_type,
      oracle::id_big_int >
    id_entityFeature_type_;

    static const id_entityFeature_type_ id_entityFeature;

    // standardName
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::std::string,
        oracle::id_string >::query_type,
      oracle::id_string >
    standardName_type_;

    static const standardName_type_ standardName;

    // displayName
    //
    typedef
    oracle::query_column<
      oracle::value_traits<
        ::std::string,
        oracle::id_string >::query_type,
      oracle::id_string >
    displayName_type_;

    static const displayName_type_ displayName;
  };

  template <const char* table>
  const typename query_columns< ::UniPAX::EntityReference, table >::entityReferenceType_type_
  query_columns< ::UniPAX::EntityReference, table >::entityReferenceType (table, "\"entityReferenceType\"", 20);

  template <const char* table>
  const typename query_columns< ::UniPAX::EntityReference, table >::id_entityFeature_type_
  query_columns< ::UniPAX::EntityReference, table >::id_entityFeature (table, "\"id_entityFeature\"", 20);

  template <const char* table>
  const typename query_columns< ::UniPAX::EntityReference, table >::standardName_type_
  query_columns< ::UniPAX::EntityReference, table >::standardName (table, "\"standardName\"", 512);

  template <const char* table>
  const typename query_columns< ::UniPAX::EntityReference, table >::displayName_type_
  query_columns< ::UniPAX::EntityReference, table >::displayName (table, "\"displayName\"", 512);

  struct access::object_traits< ::UniPAX::EntityReference >::query_type:
    query_base_type,
    query_columns< ::UniPAX::EntityReference, table_name >
  {
    query_type ();
    query_type (bool);
    query_type (const char*);
    query_type (const std::string&);
    query_type (const query_base_type&);
  };
}

#include <UNIPAX/PERSISTENCE/ORACLE/BIOPAX/EntityReference-odb.ixx>

// Begin epilogue.
//
//
// End epilogue.

#include <odb/post.hxx>

#endif // ENTITY_REFERENCE_ODB_HXX
