/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

SET FEEDBACK OFF;
WHENEVER SQLERROR EXIT FAILURE;
WHENEVER OSERROR EXIT FAILURE;

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway_id_pathwayOrder" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_id_pathwayOrder_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_id_pathwayOrder_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway_id_pathwayComponent" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_id_pathwayComponent_se"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_id_pathwayComponent_tr"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway_id_modelExtensions" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_id_modelExtensions_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_id_modelExtensions_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway_id_xref" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_id_xref_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_id_xref_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway_name" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_name_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_name_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway_comments" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_comments_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_comments_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/

BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Pathway" CASCADE CONSTRAINTS';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE "Pathway_seq"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE; END IF;
  END;
  BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER "Pathway_trg"';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN RAISE; END IF;
  END;
END;
/


CREATE TABLE "Pathway" (
  "unipaxId" NUMBER(20) NOT NULL PRIMARY KEY,
  "unipaxSource" NUMBER(20),
  "availability" VARCHAR2(512),
  "standardName" VARCHAR2(512),
  "displayName" VARCHAR2(512),
  "evidence" NUMBER(20),
  "dataSource" NUMBER(20),
  "organism" NUMBER(20));

CREATE TABLE "Pathway_comments" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" VARCHAR2(512),
  CONSTRAINT "Pathway_comments_object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "Pathway" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "Pathway_comments_object_id_i"
  ON "Pathway_comments" ("object_id");

CREATE INDEX "Pathway_comments_index_i"
  ON "Pathway_comments" ("index");

CREATE TABLE "Pathway_name" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" VARCHAR2(512),
  CONSTRAINT "Pathway_name_object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "Pathway" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "Pathway_name_object_id_i"
  ON "Pathway_name" ("object_id");

CREATE INDEX "Pathway_name_index_i"
  ON "Pathway_name" ("index");

CREATE TABLE "Pathway_id_xref" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" NUMBER(20) NOT NULL,
  CONSTRAINT "Pathway_id_xref_object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "Pathway" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "Pathway_id_xref_object_id_i"
  ON "Pathway_id_xref" ("object_id");

CREATE INDEX "Pathway_id_xref_index_i"
  ON "Pathway_id_xref" ("index");

CREATE TABLE "Pathway_id_modelExtensions" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" NUMBER(20) NOT NULL,
  CONSTRAINT "Pathway_id_modelExtensions_obj"
    FOREIGN KEY ("object_id")
    REFERENCES "Pathway" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "Pathway_id_modelExtensions_obj"
  ON "Pathway_id_modelExtensions" ("object_id");

CREATE INDEX "Pathway_id_modelExtensions_ind"
  ON "Pathway_id_modelExtensions" ("index");

CREATE TABLE "Pathway_id_pathwayComponent" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" NUMBER(20) NOT NULL,
  CONSTRAINT "Pathway_id_pathwayComponent_ob"
    FOREIGN KEY ("object_id")
    REFERENCES "Pathway" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "Pathway_id_pathwayComponent_ob"
  ON "Pathway_id_pathwayComponent" ("object_id");

CREATE INDEX "Pathway_id_pathwayComponent_in"
  ON "Pathway_id_pathwayComponent" ("index");

CREATE TABLE "Pathway_id_pathwayOrder" (
  "object_id" NUMBER(20) NOT NULL,
  "index" NUMBER(20) NOT NULL,
  "value" NUMBER(20) NOT NULL,
  CONSTRAINT "Pathway_id_pathwayOrder_object"
    FOREIGN KEY ("object_id")
    REFERENCES "Pathway" ("unipaxId")
    ON DELETE CASCADE);

CREATE INDEX "Pathway_id_pathwayOrder_object"
  ON "Pathway_id_pathwayOrder" ("object_id");

CREATE INDEX "Pathway_id_pathwayOrder_index_"
  ON "Pathway_id_pathwayOrder" ("index");

ALTER TABLE "Pathway" ADD
  CONSTRAINT "Pathway_unipaxSource_fk"
    FOREIGN KEY ("unipaxSource")
    REFERENCES "ImportSource" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "Pathway" ADD
  CONSTRAINT "Pathway_evidence_fk"
    FOREIGN KEY ("evidence")
    REFERENCES "Evidence" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "Pathway" ADD
  CONSTRAINT "Pathway_dataSource_fk"
    FOREIGN KEY ("dataSource")
    REFERENCES "Provenance" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "Pathway" ADD
  CONSTRAINT "Pathway_organism_fk"
    FOREIGN KEY ("organism")
    REFERENCES "BioSource" ("unipaxId")
    DEFERRABLE INITIALLY DEFERRED;

EXIT;
