cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/UPBase.sql > ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/SBase.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Thing.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Rule.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Entity.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/UtilityClass.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Interaction.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/PhysicalEntity.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ControlledVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/CellularLocationVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/EntityFeature.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/EntityReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/PathwayStep.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SequenceLocation.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Xref.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Control.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Conversion.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/BiochemicalReaction.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/BindingFeature.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/BiochemicalPathwayStep.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/BioSource.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Catalysis.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/CellVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ChemicalStructure.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ComplexAssembly.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Complex.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/CovalentBindingFeature.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Degradation.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/DeltaG.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Dna.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/DnaReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/DnaRegion.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/DnaRegionReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/EntityReferenceTypeVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/EvidenceCodeVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Evidence.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ExperimentalForm.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ExperimentalFormVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/FragmentFeature.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Gene.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/GeneticInteraction.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/InteractionVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/KPrime.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ModificationFeature.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Modulation.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/MolecularInteraction.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Pathway.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/PhenotypeVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Protein.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/ProteinReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Provenance.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/PublicationXref.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/RelationshipTypeVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/RelationshipXref.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Rna.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/RnaReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/RnaRegion.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/RnaRegionReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Score.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SequenceInterval.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SequenceModificationVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SequenceRegionVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SequenceSite.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SmallMolecule.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/SmallMoleculeReference.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Stoichiometry.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/TemplateReaction.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/TemplateReactionRegulation.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/TissueVocabulary.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/Transport.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/TransportWithBiochemicalReaction.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/BIOPAX/UnificationXref.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/AlgebraicRule.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/AssignmentRule.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Constraint.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/DataMatrix.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Delay.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/EventAssignment.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Event.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Experiment.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/FunctionDefinition.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/IdMapping.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/ImportSource.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/InitialAssignment.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/KineticLaw.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/LocalParameter.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Math.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Model.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Parameter.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Priority.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/RateRule.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/ResultObject.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Sample.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/SampleData.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Series.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Trigger.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/UnitDefinition.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql
cat ../include/UNIPAX/PERSISTENCE/MYSQL/EXT/Unit.sql >> ../include/UNIPAX/PERSISTENCE/MYSQL/UniPAX_MySQL.sql

