SET(SOURCES_LIST
BindingFeature.cpp
BioSource.cpp
BiochemicalPathwayStep.cpp
BiochemicalReaction.cpp
Catalysis.cpp
CellVocabulary.cpp
CellularLocationVocabulary.cpp
ChemicalStructure.cpp
Complex.cpp
ComplexAssembly.cpp
Control.cpp
ControlledVocabulary.cpp
Conversion.cpp
CovalentBindingFeature.cpp
Degradation.cpp
DeltaG.cpp
Dna.cpp
DnaReference.cpp
DnaRegion.cpp
DnaRegionReference.cpp
Entity.cpp
EntityFeature.cpp
EntityReference.cpp
EntityReferenceTypeVocabulary.cpp
Evidence.cpp
EvidenceCodeVocabulary.cpp
ExperimentalForm.cpp
ExperimentalFormVocabulary.cpp
FragmentFeature.cpp
Gene.cpp
GeneticInteraction.cpp
Interaction.cpp
InteractionVocabulary.cpp
KPrime.cpp
ModificationFeature.cpp
Modulation.cpp
MolecularInteraction.cpp
Pathway.cpp
PathwayStep.cpp
PhenotypeVocabulary.cpp
PhysicalEntity.cpp
Protein.cpp
ProteinReference.cpp
Provenance.cpp
PublicationXref.cpp
RelationshipTypeVocabulary.cpp
RelationshipXref.cpp
Rna.cpp
RnaReference.cpp
RnaRegion.cpp
RnaRegionReference.cpp
Score.cpp
SequenceInterval.cpp
SequenceLocation.cpp
SequenceModificationVocabulary.cpp
SequenceRegionVocabulary.cpp
SequenceSite.cpp
SmallMolecule.cpp
SmallMoleculeReference.cpp
Stoichiometry.cpp
TemplateReaction.cpp
TemplateReactionRegulation.cpp
Thing.cpp
TissueVocabulary.cpp
Transport.cpp
TransportWithBiochemicalReaction.cpp
UnificationXref.cpp
UtilityClass.cpp
Xref.cpp
)

ADD_UNIPAX_SOURCES("KERNEL/BIOPAX" "${SOURCES_LIST}")
